### ISSUE TITLE
im getting "Access is denied."

### ISSUE THREAD

**Issue by aoshi120** [PS3Xploit/PS3xploit-resigner#6]
hello, 

I put act.dat and idps.hex in the .\PS3xploit-resigner-2.0.0\rifgen-master folder.
I put my rap file in the raps folder and execute resign_all.bat 
and it look like the ps3xploit_rifgen_edatresign is getting access problems, as is displaying "Access is denied." and is not creating the pkg file.

![image](https://user-images.githubusercontent.com/37517042/37571119-031ed374-2abe-11e8-802b-12f1cdcf1c0d.png)

**Comment by ju27pmg** [comment]
Have you ran it with admin?

**Comment by PS3Xploit** [comment]
your path is somehow protected, use admin or change folders

**Comment by Caio99BR** [comment]
It's because the slash and backslash, I'm working to fix it

**Comment by assegaf** [comment]
@Caio99BR thanks, we are not all windows user, is it possible to make binary dan include it in package pkg_exdata.exe binary requivalent for linux also ?

**Comment by Caio99BR** [comment]
@assegaf I already made a version of script to Linux (I prefer it over windows) and picked original python file (yeah the pkg_exdata.exe is a executable of pkg_exdata.py from Aldostools PS3 Tools Collection (or other idk) with Python built-in) and adapted to build a PKG License (Changed one line XD).

Now Im rewriting the windows script (hard as hell because I only know BASH), testing a new feature to sign pkgs and polishing everything.

PS: My Win10 hanged when I was finishing tests.

TODO: Remove that getchar(), why did you put that @PS3Xploit? (Also learn how to build a new .exe)

**Comment by PS3Xploit** [comment]
It’s not because of backslash etc
The error occurred because of the exdata exe execution failure. I tried it on win 10 x64 and it doesn’t seem to cause any issues

getchar is there to prevent screen screen closure without user input but I already made an update to prevent that when batch is running + few changes for a future han release ;)

**Comment by Caio99BR** [comment]
`
The error occurred because of the exdata exe execution failure. I tried it on win 10 x64 and it doesn’t seem to cause any issues
`
I mean that \./

But anyway, I could open a Pull Request any time?

**Comment by Caio99BR** [comment]
Fixed on #10, please give a try on https://github.com/Caio99BR/PS3xploit-resigner and send results.

**Comment by aoshi120** [comment]
hello Caio/team,

with this version I was able to create the pkg file PKG_RIF-INSTALLER.pkg_signed.pkg inside \output\rif_pkg

thank you

**Comment by Caio99BR** [comment]
You're welcome, you can close this issue when PR #10 get merged or a better solution committed :)

**Comment by PS3Xploit** [comment]
Nice one! :)
Merged!

**Comment by Caio99BR** [comment]
You're welcome :D 
Just making what's possible to me do.
